behaviors:
  BasicDiverse:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 100000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 10.0
      mede: True
      mede_dropout: 0
      mede_encoder_dropout: 0.1
      mede_weight_decay: 0
      mede_saliency_dropout: 0
      mede_strength: 0.05
      mede_mutual_information: .inf
      mede_for_policy_loss: True
      mede_use_actions: True
      mede_drop_actions: True
      mede_noise: True
      mede_centered: False
    network_settings:
      normalize: false
      hidden_units: 16
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
