behaviors:
  GridDiverse:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.001
      learning_rate_schedule: constant
      batch_size: 32
      buffer_size: 10000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 5.0
      diayn: True
      mede_init_divcoef: 0.05
      mede_target_divcoef: 0.05
    network_settings:
      normalize: false
      hidden_units: 8
      num_layers: 1
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 32
    summary_freq: 10000
    checkpoint_interval: 50000
