behaviors:
  LaserMazeDiverse:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 100000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 10.0
      diayn: True
      mede_continuous: False
      mede_init_divcoef: 0.05
      mede_target_divcoef: 0.05
      mede_divcoef_lr: 0.000001
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 50000
    checkpoint_interval: 200000
env_settings:
  seed: 2
