behaviors:
  3DBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 5000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 5000
    summary_freq: 10000

environment_parameters:
  maxStep: 1000
  rewardType: 1
  numParallel: 18
  decisionFreq: 5
  
