behaviors:
  Walker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003 #03
      beta: 0.002 #0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256 #512
      num_layers: 3
      vis_encode_type: simple
      # memory:
      #   sequence_length: 32
      #   memory_size: 64
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      # curiosity:
      #   gamma: 0.995
      #   strength: 0.1
      #   network_settings:
      #     hidden_units: 256
      #   learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 100 #500
    summary_freq: 3000
