behaviors:
  A1Skill:
    trainer_type: ase
    hyperparameters:
      latent_dim: 32
      latent_steps_min: 1
      latent_steps_max: 500
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      gae_lambda: 0.95
      td_lambda: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 50
    even_checkpoints: true
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
#    behavioral_cloning:
#      demo_path: /Users/miguel.alonso/Projects/ML-Agents Atlas Soccer/Demos/Standing.demo
#      steps: 1000000
#      strength: 1.0
#      samples_per_update: 0
env_settings:
#   num_envs: 8
   num_areas: 8
