behaviors:
  A1Skill:
    trainer_type: ase
    hyperparameters:
      batch_size: 1024
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      ase:
        latent_dim: 2
        latent_steps_min: 1
        latent_steps_max: 100
        batch_size: 1024
        demo_path: /home/miguelalonsojr/Projects/rle/Demos/A1
        learning_rate: 0.0003
        network_settings:
          normalize: true
          hidden_units: 512
          num_layers: 3
          vis_encode_type: simple
    keep_checkpoints: 50
    even_checkpoints: true
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
#    behavioral_cloning:
#      demo_path: /Users/miguel.alonso/Projects/ML-Agents Atlas Soccer/Demos/Standing.demo
#      steps: 1000000
#      strength: 1.0
#      samples_per_update: 0
env_settings:
#   num_envs: 8
   num_areas: 8
