behaviors:
  WalkerASE:
    trainer_type: ase
    hyperparameters:
      batch_size: 4096
      buffer_size: 32768
      learning_rate: 0.000025
      beta: 0.0025
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      ase:
        latent_dim: 4
        latent_steps_min: 1
        latent_steps_max: 50
        beta_sdo: 0.5
        omega_do: 0.01
        encoder_scaling: 1.0
        batch_size: 1024
        demo_path: /Users/miguel.alonso/Products/ml-agents/Project/Assets/ML-Agents/Examples/Walker/Demos/ASE
        learning_rate: 0.000025
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
    keep_checkpoints: 100
    even_checkpoints: true
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
#    behavioral_cloning:
#      demo_path: /Users/miguel.alonso/Projects/ML-Agents Atlas Soccer/Demos/Standing.demo
#      steps: 1000000
#      strength: 1.0
#      samples_per_update: 0
env_settings:
#   num_envs: 8
   num_areas: 8
